;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Effect.Damage",DevComment="이펙트 데미지 설정용")
+GameplayTagList=(Tag="Element.Fire",DevComment="불속성")
+GameplayTagList=(Tag="Element.Ice",DevComment="얼음속성")
+GameplayTagList=(Tag="State.Debuff.Burn",DevComment="화상 버프 불속성에 추가 대미지 입음")
+GameplayTagList=(Tag="State.Debuff.Freez",DevComment="빙결 버프 얼음 속성에 추가 데미지 입음")

